### ISSUE TITLE
Add SSR Support

### ISSUE THREAD

**Issue by bshelkhonov** [telegram-mini-apps-dev/TelegramUI#12]
I'm making my application in NextJS. 
Code fails to compile because of this line: https://github.com/XeleneStudio/TelegramUI/blob/main/src/components/Service/AppRoot/hooks/useAppearance.ts#L17

```
node_modules/@xelene/tgui/dist/helpers/telegram.js (3:4) @ getTelegramData
Internal error: ReferenceError: window is not defined
at getTelegramData (./node_modules/@xelene/tgui/dist/helpers/telegram.js:7:5)
at useAppearance (./node_modules/@xelene/tgui/dist/components/Service/AppRoot/hooks/useAppearance.js:20:92)
at eval (./node_modules/@xelene/tgui/dist/components/Service/AppRoot/AppRoot.js:41:156)
```

**Comment by mainsmirnov** [comment]
Hi, we fixed this issue in version 2.0.6

https://github.com/XeleneStudio/TelegramUI/commit/8eceb90c86e2b0eb0b2cb0dbbf073949f660bfcb
